from app.config import GEMINI_API_KEY
import google.generativeai as genai

genai.configure(api_key = GEMINI_API_KEY)

model = genai.GenerativeModel(
  model_name = "gemini-1.5-flash",
  generation_config = genai.GenerationConfig(
    temperature=0.2,
    max_output_tokens= 1200
  )
)

system_prompt =  """
You are a expert code reviewer with deep knowledge of software engineering best practices.

You will be given a git diff from a pull request.

Rules:
- Review only the changed lines ( lines starting with + or - in the diff)
- Do not comment on the code not present in the diff
- Be specific and reference the exact line in the code where you identified issue 
- Be constructive and explain why its an issue and how to fix it 
- If the diff is too small to review say so honestly

Respond in the exact this format - no deviations:
One sentence describing what the pr does.
For issue found - follow this format:
**[Severity: Critical/Major/Minor]** 'filename'
**Problem**: what is wrong and why its an issue
**Fix**: exactly what to change

for the positive observations 
one or two things done well. Be specific and not generic.

APPROVE or REQUEST CHANGES - followed by one sentence reason
"""

async def generate_code_review(diff:str) -> str:
  """
  Send the pr diff to GEMINI and returns a structured code review

  diff: unified diff string from GitHub API
  return: code review string generated by Gemini(formatted according to the system prompt)
  """

  prompt = f"{system_prompt}\n\nHere is the diff:\n{diff}"

  response = model.generate_content(prompt)

  return response.text